const COINS_API_ENDPOINT = process.env.COINS_API_ENDPOINT;
const TMP_ENDPOINT = COINS_API_ENDPOINT + "/tmp";
const NEW_TASK_ENDPOINT = COINS_API_ENDPOINT + "/tasks/new";
const BOT_REGISTRATION_ENDPOINT = COINS_API_ENDPOINT + "/bot/register";
const BOT_HOME_ENDPOINT = COINS_API_ENDPOINT + "/bot/home";

module.exports = {
  COINS_API_ENDPOINT,
  TMP_ENDPOINT,
  NEW_TASK_ENDPOINT,
  BOT_REGISTRATION_ENDPOINT,
  BOT_HOME_ENDPOINT,
};
