const COINS_API_ENDPOINT = process.env.COINS_API_ENDPOINT;
const TMP_ENDPOINT = COINS_API_ENDPOINT + "/tmp";
const SOLVE_TASK_ENDPOINT = COINS_API_ENDPOINT + "/bot/tasks/{task_id}/solve";
const BOT_REGISTRATION_ENDPOINT = COINS_API_ENDPOINT + "/bot/register";
const BOT_HOME_ENDPOINT = COINS_API_ENDPOINT + "/bot/home";
const NEW_TASK_ENDPOINT = COINS_API_ENDPOINT + "/bot/new-task";

module.exports = {
  COINS_API_ENDPOINT,
  TMP_ENDPOINT,
  NEW_TASK_ENDPOINT,
  SOLVE_TASK_ENDPOINT,
  BOT_REGISTRATION_ENDPOINT,
  BOT_HOME_ENDPOINT,
};
