const COINS_API_ENDPOINT = process.env.COINS_API_ENDPOINT;
const TMP_ENDPOINT = COINS_API_ENDPOINT + "/tmp";
const NEW_TASK_ENDPOINT = COINS_API_ENDPOINT + "/tasks/new";

module.exports = {
  COINS_API_ENDPOINT,
  TMP_ENDPOINT,
  NEW_TASK_ENDPOINT,
};