spring:
  datasource:
    url: jdbc:${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  output:
    ansi:
      enabled: always
  jackson:
    serialization:
      indent_output: true
jooq:
  sql-dialect:Postgres
logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: DEBUG
teamsbot:
  endpoint: ${TEAMS_BOT_ENDPOINT}
server:
  port: 8080
usos:
  apiKey: ${USOS_API_KEY}
  apiSecret: ${USOS_API_SECRET}