spring:
  datasource:
    url: jdbc:${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
jooq:
  sql-dialect:Postgres
sql:
  init:
    platform: postgres
logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: DEBUG
teamsbot:
  endpoint: ${TEAMS_BOT_ENDPOINT}
server:
  port: 8080